version: '2'
services:
  statusok:
    build: .
    container_name: statusok
    tty: true
    volumes:
      - ./config:/config
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes: 
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB="statusok"
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      # - ./grafana-plugins:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=tim.tawan@signaturegroup.com.au
      - GF_SMTP_PASSWORD=@@Root1234
      - GF_SMTP_FROM_ADDRESS=monitoring@signaturegroup.com.au

volumes:
  influxdb-storage:
  grafana-storage:
      